version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd my-first-pipeline
      - npm install 
  pre_build:
    commands:
      - echo "Running tests... "
      - npm test 
  build:
    commands:
      - echo "Creating artifact..."
      - zip -r my-app.zip . -x "*.git*" -x "node_modules/*"
      - echo "Artifact created!"
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
     - my-first-pipeline/my-app.zip
  name: my-build-artifact
