version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd my-first-pipeline
      - npm install 
  pre_build:
    commands:
      - echo "Running tests... "
      - cd my-first-pipeline
      - npm test 
  build:
    commands:
      - echo "Build completed !"
artifacts:
  files:
    - '**/*'
